import test from 'node:test'
import assert from 'node:assert/strict'
import { CAMPAIGN_STATUSES,createCampaign,transitionCampaign } from '../src/marketing/campaignDomain.js'
import { assertApprovalMatchesArtifact,createApprovalDecision } from '../src/marketing/approvals.js'
import { createArtifactRecord } from '../src/marketing/artifacts.js'

test('campaign has complete lifecycle and keeps execution context',()=>{const c=createCampaign({userId:'u1',projectId:'p1',name:'Launch',audience:'Founders',offer:'Audit',budget:1000,channels:['linkedin','linkedin']},{id:'c1'});assert.deepEqual(CAMPAIGN_STATUSES,['draft','planned','active','paused','completed','archived']);assert.deepEqual(c.context.channels,['linkedin']);assert.equal(transitionCampaign(c,'planned').status,'planned');assert.throws(()=>transitionCampaign(c,'active'),/Invalid campaign transition/)})
test('approval binds actor tenant and immutable artifact version',()=>{const a=createArtifactRecord({userId:'u1',projectId:'p1',type:'copy',purpose:'Launch',content:{headline:'A'}},{id:'a1'});const d=createApprovalDecision({userId:'u1',projectId:'p1',artifactId:'a1',artifactVersion:1,decision:'approved'},{id:'d1'});assert.equal(assertApprovalMatchesArtifact(d,a),true);assert.throws(()=>assertApprovalMatchesArtifact({...d,projectId:'p2'},a),e=>e.code==='STALE_OR_FORGED_APPROVAL');assert.throws(()=>assertApprovalMatchesArtifact({...d,artifactVersion:2},a),e=>e.code==='STALE_OR_FORGED_APPROVAL')})
test('approval rejects forged actors and unsupported decisions',()=>{assert.throws(()=>createApprovalDecision({userId:'u',projectId:'p',artifactId:'a',artifactVersion:1,decision:'publish'}),/Unsupported/);assert.throws(()=>createApprovalDecision({userId:'u',projectId:'p',artifactId:'a',artifactVersion:0,decision:'approved'}),/version/)})
