import test from 'node:test'
import assert from 'node:assert/strict'
import {createGracefulShutdown,databaseSslForRuntime,databaseUrlForRuntime,strictTestMode,verifyStrictTestDatabase} from '../src/services/databaseStartup.js'

const migrations=[{name:'2026-01-01_core.sql',checksum:'abc'}]
function client({database='yeeyoo_phase13_test',checksum='abc',missingColumn=false}={}){const calls=[];return{calls,async query(sql){calls.push(sql);if(sql.includes('current_database'))return{rows:[{name:database}]};if(sql.includes('schema_migrations'))return{rows:[{name:migrations[0].name,checksum}]};if(sql.includes('information_schema.columns')){const required={users:['id','email'],projects:['id','user_id'],auth_sessions:['id','user_id','access_hash','revoked_at'],ai_jobs:['id','user_id','project_id','status'],project_activity:['id','user_id','project_id','event_type']};const rows=Object.entries(required).flatMap(([table_name,cols])=>cols.map(column_name=>({table_name,column_name})));return{rows:missingColumn?rows.slice(1):rows}};throw new Error(`unexpected SQL ${sql}`)}}}
test('strict mode requires all explicit gates and uses only test URL',()=>{const env={NODE_ENV:'test',YEEYOO_STRICT_TEST_DB:'true',YEEYOO_TEST_DATABASE_URL:'test-url',DATABASE_URL:'production-url'};assert.equal(strictTestMode(env),true);assert.equal(databaseUrlForRuntime(env),'test-url');assert.throws(()=>databaseUrlForRuntime({...env,YEEYOO_TEST_DATABASE_URL:''}),/requires YEEYOO_TEST_DATABASE_URL/)})
test('strict disposable database uses TLS without changing local development',()=>{assert.deepEqual(databaseSslForRuntime({NODE_ENV:'test',YEEYOO_STRICT_TEST_DB:'true'}),{rejectUnauthorized:false});assert.equal(databaseSslForRuntime({NODE_ENV:'development'}),false)})
test('strict verifier is read-only and accepts exact complete ledger/schema',async()=>{const db=client();const result=await verifyStrictTestDatabase(db,{migrations});assert.equal(result.readOnly,true);assert.ok(db.calls.every(sql=>/^SELECT\b/i.test(sql.trim())));assert.equal(result.database,'yeeyoo_phase13_test')})
test('strict verifier rejects database mismatch, checksum drift and missing compatibility',async()=>{await assert.rejects(verifyStrictTestDatabase(client({database:'postgres'}),{migrations}),/identity rejected/);await assert.rejects(verifyStrictTestDatabase(client({checksum:'tampered'}),{migrations}),/Applied migration changed/);await assert.rejects(verifyStrictTestDatabase(client({missingColumn:true}),{migrations}),/compatibility check failed/)})
test('graceful shutdown is idempotent and bounded',async()=>{let ends=0;const exits=[];const shutdown=createGracefulShutdown({pool:{end:async()=>{ends++}},exit:(code,signal)=>exits.push([code,signal]),timeoutMs:100});await Promise.all([shutdown('SIGTERM'),shutdown('SIGINT')]);assert.equal(ends,1);assert.deepEqual(exits,[[0,'SIGTERM']])})
test('graceful shutdown reports timeout failure',async()=>{const exits=[];const shutdown=createGracefulShutdown({pool:{end:()=>new Promise(()=>{})},exit:(code)=>exits.push(code),timeout:(fn)=>{fn();return 1},clear:()=>{}});await shutdown();assert.deepEqual(exits,[1])})
