import test from 'node:test'
import assert from 'node:assert/strict'
import {PHASE19,assertPhase19Database,seedPhase19Fixture} from '../src/services/phase19Fixture.js'
import {enqueueArtifact} from '../src/marketing/artifactWorkflow.js'
import {mockPublishingAdapter} from '../src/publishing/mockAdapter.js'
import {recordProjectActivity} from '../src/lib/projectActivity.js'
import {recordPerformanceEvent,summarizePerformance} from '../src/marketing/performanceEvents.js'
import {createArtifactRecord} from '../src/marketing/artifacts.js'
import {createApprovalDecision,assertApprovalMatchesArtifact} from '../src/marketing/approvals.js'

test('fixture rejects every non-exact database before writes',async()=>{let writes=0;const db={query:async sql=>{if(sql.includes('current_database'))return{rows:[{name:'postgres'}]};writes++;return{rows:[]}}};await assert.rejects(seedPhase19Fixture(db),/identity rejected/);assert.equal(writes,0)})
test('fixture seed is transaction-bound and deterministically scoped',async()=>{const calls=[];const db={query:async(sql,params=[])=>{calls.push({sql,params});if(sql.includes('current_database'))return{rows:[{name:'yeeyoo_phase13_test'}]};return{rows:[]}}};assert.equal(await assertPhase19Database(db),'yeeyoo_phase13_test');await seedPhase19Fixture(db);assert.equal(calls.filter(x=>x.sql==='BEGIN').length,1);assert.equal(calls.filter(x=>x.sql==='COMMIT').length,1);assert.ok(calls.some(x=>x.params.includes(PHASE19.projectId)));assert.ok(calls.every(x=>!x.params.includes('20000000-0000-4000-8000-000000000001')))
})
test('artifact v2 approval, queue, publish activity and reporting contracts compose idempotently',async()=>{const artifact=createArtifactRecord({id:PHASE19.artifactV2Id,rootId:PHASE19.artifactRootId,userId:PHASE19.userId,projectId:PHASE19.projectId,campaignId:PHASE19.campaignId,type:'copy',artifactVersion:2,purpose:'Phase19 loop',channel:'linkedin',content:{socialCopy:'Approved deterministic copy'},provenance:{marketingProfileVersion:2}});artifact.status='approved';const decision=createApprovalDecision({userId:PHASE19.userId,projectId:PHASE19.projectId,campaignId:PHASE19.campaignId,artifactId:artifact.id,artifactVersion:2,checksumVersion:artifact.checksumVersion,contentChecksum:artifact.contentChecksum,outputChecksum:artifact.outputChecksum,decision:'approved',artifact});assertApprovalMatchesArtifact(decision,artifact);let queued=false;const db={query:async(sql)=>{if(sql.includes('INSERT INTO posts')){if(queued)return{rows:[{id:'post1',status:'approved'}]};queued=true;return{rows:[{id:'post1',status:'approved'}]};}if(sql.includes('INSERT INTO project_activity'))return{rows:[{id:'act1'}]};if(sql.includes('INSERT INTO marketing_performance_events'))return{rows:[{kind:'publish_succeeded',unit:'count',value:1}]};throw new Error(sql)}};const first=await enqueueArtifact({artifact,db}),second=await enqueueArtifact({artifact,db});assert.equal(first.id,second.id);const published=await mockPublishingAdapter.publish({post:first,idempotencyKey:`${PHASE19.userId}:${first.id}`});assert.equal(published.status,'published');assert.ok(await recordProjectActivity({userId:PHASE19.userId,projectId:PHASE19.projectId,eventType:'content_published',summary:'Mock content published',dedupeKey:'publish:post1',db}));const event=await recordPerformanceEvent({userId:PHASE19.userId,projectId:PHASE19.projectId,campaignId:PHASE19.campaignId,artifactId:artifact.id,kind:'publish_succeeded',source:{provider:'mock-local',externalEventId:'post1'}},{db});assert.equal(summarizePerformance([event]).totals['publish_succeeded:count'],1)})
test('mock publish failure is deterministic and recoverable with same idempotency key',async()=>{await assert.rejects(mockPublishingAdapter.publish({post:{content:'[MOCK_PUBLISH_FAIL]'},idempotencyKey:'same-key'}),/Mock publish failure/);const retry=await mockPublishingAdapter.publish({post:{content:'recovered'},idempotencyKey:'same-key'});assert.equal(retry.externalId,'mock_same-key')})
