import test from 'node:test'
import assert from 'node:assert/strict'
import {approvalFingerprint} from '../src/tony/autopilotPolicy.js'
import {consumeApprovalEnvelope} from '../src/tony/approvalStore.js'

const now=Date.parse('2026-06-01T12:00:00Z'),context={userId:'u1',projectId:'p1',campaignId:'c1',planId:'plan1',artifactId:'a1',artifactVersion:1,budget:10,currency:'NOK',channels:['mock'],providerConnected:true,providerConnectionId:'conn',providerConnectionVersion:1,approvalNonce:'nonce'}
const approval={id:'approval',status:'approved',action:'publish',user_id:'u1',project_id:'p1',campaign_id:'c1',approved_by_user_id:'owner',approved_at:'2026-06-01T11:00:00Z',expires_at:'2026-06-01T13:00:00Z',nonce:'nonce',fingerprint:approvalFingerprint({...context,action:'publish',policyVersion:1}),consumed_at:null,revoked_at:null}
function database({existingAudit=false,approvalRow=approval}={}){const state={queries:[],committed:false,rolledBack:false,consumed:false};const client={async query(sql,params=[]){state.queries.push({sql,params});if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK'){if(sql==='COMMIT')state.committed=true;if(sql==='ROLLBACK')state.rolledBack=true;return{rows:[]}}if(sql.includes('FROM autopilot_action_audit'))return{rows:existingAudit?[{decision:'allowed',decision_code:'AUTHORIZED'}]:[]};if(sql.includes('FROM autopilot_action_approvals'))return{rows:approvalRow?[approvalRow]:[]};if(sql.includes('FROM autopilot_policies'))return{rows:[{level:3,version:1,max_budget:10,currency:'NOK',channels:['mock'],project_id:'p1',campaign_id:'c1'}]};if(sql.includes('UPDATE autopilot_action_approvals')){if(state.consumed)return{rows:[]};state.consumed=true;return{rows:[{id:'approval'}]}}if(sql.includes('INSERT INTO autopilot_action_audit'))return{rows:[]};throw new Error(sql)},release(){}};return{state,connect:async()=>client}}

test('approval consumes and audits atomically before caller may execute',async()=>{const db=database();const result=await consumeApprovalEnvelope({approvalId:'approval',userId:'u1',projectId:'p1',campaignId:'c1',action:'publish',context,idempotencyKey:'key1',now,db});assert.equal(result.allowed,true);assert.equal(db.state.consumed,true);assert.equal(db.state.committed,true);const sql=db.state.queries.map(q=>q.sql).join('\n');assert.match(sql,/FOR UPDATE/);assert.match(sql,/consumed_at IS NULL/);assert.match(sql,/INSERT INTO autopilot_action_audit/)})
test('duplicate action key returns inert replay without consuming twice',async()=>{const db=database({existingAudit:true});const result=await consumeApprovalEnvelope({approvalId:'approval',userId:'u1',projectId:'p1',campaignId:'c1',action:'publish',context,idempotencyKey:'same',now,db});assert.deepEqual(result,{allowed:false,duplicate:true,code:'ACTION_REPLAY_DENIED'});assert.equal(db.state.consumed,false)})
test('cross-tenant context is rejected before database access',async()=>{let connected=false;await assert.rejects(consumeApprovalEnvelope({approvalId:'approval',userId:'u1',projectId:'p1',campaignId:'c1',action:'publish',context:{...context,userId:'u2'},idempotencyKey:'key',db:{connect:async()=>{connected=true}}}),error=>error.code==='APPROVAL_SCOPE_MISMATCH');assert.equal(connected,false)})
test('stale fingerprint is denied, audited, and never consumed',async()=>{const db=database({approvalRow:{...approval,fingerprint:'0'.repeat(64)}});const result=await consumeApprovalEnvelope({approvalId:'approval',userId:'u1',projectId:'p1',campaignId:'c1',action:'publish',context,idempotencyKey:'key',now,db});assert.equal(result.allowed,false);assert.equal(result.code,'APPROVED_STATE_CHANGED');assert.equal(db.state.consumed,false);assert.equal(db.state.committed,true)})
