import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs'
import{SOSY_IDENTITY}from'../src/sosy/identity.js';import{buildSosyDraft,createSosyDelegation,normalizeChannels,normalizeLanguages,transitionSosyDelegation}from'../src/sosy/domain.js';import{getSosyDelegation,listSosyDelegations}from'../src/sosy/store.js'
const base={userId:'user-a',projectId:'project-a',taskType:'content.create',objective:'Launch story',channels:['Instagram','linkedin','instagram'],languages:{conversationLanguage:'nb_NO',outputLanguage:'en-us'}}
test('Sosy has one canonical draft-only identity',()=>{assert.equal(SOSY_IDENTITY.id,'sosy');assert.equal(SOSY_IDENTITY.role,'AI Social Media Employee');assert.equal(SOSY_IDENTITY.reportsTo,'tony');assert.equal(SOSY_IDENTITY.boundaries.canPublish,false);assert.equal(SOSY_IDENTITY.boundaries.canSpend,false)})
test('delegation is structured versioned and normalized',()=>{const d=createSosyDelegation(base,{id:'d1',now:'2026-08-24T00:00:00.000Z'});assert.equal(d.schemaVersion,1);assert.deepEqual(d.channels,['instagram','linkedin']);assert.deepEqual(d.languages,{conversationLanguage:'nb-NO',outputLanguage:'en-US'});assert.equal(d.status,'assigned');assert.equal(d.specialist,'sosy')})
test('adaptation requires source and creates channel-language drafts',()=>{assert.throws(()=>createSosyDelegation({...base,taskType:'content.adapt'}),{code:'SOURCE_ARTIFACT_REQUIRED'});const d=createSosyDelegation({...base,taskType:'content.adapt',sourceArtifactId:'a1'},{id:'d1'});const draft=buildSosyDraft(d,{sourceArtifact:{content:{socialCopy:'Existing idea'}}});assert.equal(draft.content.kind,'multi-channel-adaptation');assert.equal(draft.content.variants.length,2);assert.ok(draft.content.variants.every(item=>item.status==='draft'&&item.language==='en-US'))})
test('calendar task creates proposal artifact rather than posts',()=>{const d=createSosyDelegation({...base,taskType:'calendar.propose',schedule:{month:'2026-09'}},{id:'d1'});const draft=buildSosyDraft(d);assert.equal(draft.content.kind,'social-calendar-proposal');assert.equal(draft.artifactType,'social');assert.equal('publishAt'in draft.content,false);assert.equal(SOSY_IDENTITY.boundaries.requiresArtifactApproval,true)})
test('delegation status fails closed and draft waits for approval',()=>{const assigned=createSosyDelegation(base,{id:'d1'}),working=transitionSosyDelegation(assigned,'working');assert.throws(()=>transitionSosyDelegation(working,'waiting_approval'),{code:'RESULT_REQUIRED'});assert.equal(transitionSosyDelegation(working,'waiting_approval',{resultArtifactId:'a1'}).status,'waiting_approval');assert.throws(()=>transitionSosyDelegation(assigned,'completed'),{code:'INVALID_STATUS_TRANSITION'})})
test('invalid channel and language are rejected while Phase 28 channels work',()=>{assert.throws(()=>normalizeChannels(['snapchat']),{code:'INVALID_CHANNELS'});assert.deepEqual(normalizeChannels(['threads','Pinterest','youtube']),['threads','pinterest','youtube']);assert.throws(()=>normalizeLanguages({conversationLanguage:'not a language',outputLanguage:'en'}),{code:'INVALID_LANGUAGES'})})
test('store reads always scope user and project and Tony can filter delegations',async()=>{const calls=[],db={query:async(sql,params)=>{calls.push({sql,params});return{rows:[]}}};await getSosyDelegation({id:'d1',userId:'u1',projectId:'p1',db});await listSosyDelegations({userId:'u1',projectId:'p1',tonyPlanId:'t1',db});assert.ok(calls.every(c=>c.sql.includes('user_id')&&c.sql.includes('project_id')));assert.deepEqual(calls[0].params,['d1','u1','p1']);assert.match(calls[1].sql,/tony_plan_id/);assert.deepEqual(calls[1].params.slice(0,3),['u1','p1','t1'])})
test('route preserves auth ownership and approval boundary',()=>{const source=fs.readFileSync(new URL('../src/routes/sosy.js',import.meta.url),'utf8');assert.match(source,/router\.use\(authMiddleware\)/);assert.match(source,/authMiddleware\s*=\s*auth\s*,/);assert.match(source,/await requireProjectImpl\(\s*req,\s*projectId\s*\)/);assert.match(source,/requiresApproval:\s*true/);assert.doesNotMatch(source,/\.publish\(|createAd|spendAmount/)})
test('migration enforces tenant references and distinct language fields',()=>{const sql=fs.readFileSync(new URL('../migrations/2026-08-24_sosy_delegations.sql',import.meta.url),'utf8');assert.match(sql,/FOREIGN KEY\(project_id,user_id\)/);assert.match(sql,/FOREIGN KEY\(tony_plan_id,user_id,project_id\)/);assert.match(sql,/FOREIGN KEY\(result_artifact_id,user_id,project_id\)/);assert.match(sql,/conversation_language TEXT NOT NULL/);assert.match(sql,/output_language TEXT NOT NULL/)})
