import test from 'node:test'
import assert from 'node:assert/strict'
import { generateAdsPlan,generateEmailPlan,generateSeoPlan,generateSocialStrategy } from '../src/marketing/specialistAgents.js'

const context={ profile:{version:3,objectives:['Generate leads'],audiences:['Nordic founders'],offers:['Marketing OS'],keywords:['marketing automation'],channels:['linkedin','instagram']}, competitors:[{id:'c1',evidenceIds:['ev1'],observations:['Competitor has an evidence-backed guide']}], connections:[{provider:'linkedin',status:'connected'},{provider:'meta',status:'reconnect_required'},{provider:'mailchimp',status:'connected'}] }

test('social is deterministic and reports truthful connection status',()=>{const one=generateSocialStrategy({},context);assert.deepEqual(one,generateSocialStrategy({},context));assert.equal(one.channels[0].connectionStatus,'connected');assert.equal(one.channels[1].connectionStatus,'reconnect_required');assert.equal(one.executable,false);assert.deepEqual(one.provenance.evidenceIds,['ev1'])})
test('seo separates sourced observations from hypotheses',()=>{const plan=generateSeoPlan({},context);assert.equal(plan.competitorObservations[0].evidenceRequired,true);assert.equal(plan.actionPlan[0].status,'requires-provider-data');assert.equal(plan.contentGaps[0].evidence.competitorId,'c1')})
test('email never enables sending and does not fake provider status',()=>{const plan=generateEmailPlan({sequenceType:'welcome'},context);assert.equal(plan.sendPolicy,'draft-only-never-send');assert.equal(plan.providerStatus.find(item=>item.provider==='mailchimp').status,'connected');assert.equal(plan.providerStatus.find(item=>item.provider==='klaviyo').status,'not_connected');assert.ok(plan.providerStatus.every(item=>!item.sendEnabled))})
test('ads produces recommendations without ROAS claims or execution',()=>{const plan=generateAdsPlan({budget:9000,platforms:['meta','linkedin']},context);assert.equal(plan.predictedRoas,null);assert.equal(plan.budgetRecommendation.recommendationOnly,true);assert.equal(plan.budgetRecommendation.allocation.reduce((sum,item)=>sum+item.amount,0),9000);assert.ok(plan.platforms.every(item=>!item.executionEnabled))})
test('specialists remain usable with explicit truthful fallback context',()=>{const plan=generateEmailPlan({},{profile:{objectives:[],audiences:[],offers:[]}});assert.equal(plan.audience,'the project audience');assert.equal(plan.offer,'the project offer');assert.equal(plan.provenance.marketingProfileVersion,null)})
