import test from 'node:test'
import assert from 'node:assert/strict'
import {createTestSessionRouter,testSessionEnabled,TEST_TENANTS} from '../src/routes/test-session.js'

const enabled={NODE_ENV:'test',YEEYOO_ENABLE_TEST_SESSION:'true',YEEYOO_TEST_SESSION_KEY:'x'.repeat(32),YEEYOO_TEST_DATABASE_URL:'configured-not-read-by-router'}
function response(){return{statusCode:200,body:null,cookies:[],status(n){this.statusCode=n;return this},json(body){this.body=body;return this},cookie(...args){this.cookies.push(args)},set(){}}}
function handler(router){return router.stack.find(layer=>layer.route)?.route.stack[0].handle}
function db({database='yeeyoo_phase13_test',used=false,user=true}={}){const queries=[];const client={async query(sql,params){queries.push({sql,params});if(sql==='BEGIN'||sql==='COMMIT'||sql==='ROLLBACK')return{rows:[]};if(sql.includes('current_database'))return{rows:[{name:database}]};if(sql.includes('SELECT id,name,email'))return{rows:user?[{id:params[0],name:'Tenant',email:params[1],is_admin:false}]:[]};if(sql.includes('INSERT INTO auth_exchange_codes'))return{rows:used?[]:[{id:'marker'}]};throw new Error(sql)},release(){}};return{queries,connect:async()=>client}}
async function invoke({env=enabled,tenant='alpha',key=enabled.YEEYOO_TEST_SESSION_KEY,database,used,user}={}){const store=db({database,used,user});let created=0;const router=createTestSessionRouter({db:store,env,create:async()=>{created++;return{accessToken:'not-returned',refreshToken:'not-returned'}},setCookies:(res)=>res.cookies.push(['set'])});const req={body:{tenant},get:()=>key,headers:{},ip:'127.0.0.1'};const res=response();await handler(router)(req,res);return{res,store,created}}

test('bootstrap is disabled in production, development, and without explicit enable',async()=>{for(const env of [{...enabled,NODE_ENV:'production'},{...enabled,NODE_ENV:'development'},{...enabled,YEEYOO_ENABLE_TEST_SESSION:'false'}]){assert.equal(testSessionEnabled(env),false);const{res,created}=await invoke({env});assert.equal(res.statusCode,404);assert.equal(created,0)}})
test('only fixed tenant fixtures and constant secret are accepted',async()=>{assert.deepEqual(Object.keys(TEST_TENANTS),['alpha','beta']);assert.equal((await invoke({tenant:'admin'})).res.statusCode,403);assert.equal((await invoke({key:'wrong'})).res.statusCode,403)})
test('exact database identity is required before session creation',async()=>{const{res,created,store}=await invoke({database:'postgres'});assert.equal(res.statusCode,404);assert.equal(created,0);assert.ok(store.queries.some(q=>q.sql.includes('ROLLBACK')))})
test('bootstrap is one-time and session secrets never enter response body',async()=>{const first=await invoke();assert.equal(first.res.statusCode,201);assert.equal(first.created,1);assert.doesNotMatch(JSON.stringify(first.res.body),/not-returned|token|session/i);const replay=await invoke({used:true});assert.equal(replay.res.statusCode,409);assert.equal(replay.created,0)})
test('fixture lookup binds deterministic user id and invalid email',async()=>{const{store}=await invoke({tenant:'beta'});const lookup=store.queries.find(q=>q.sql.includes('SELECT id,name,email'));assert.deepEqual(lookup.params,[TEST_TENANTS.beta,'beta@yeeyoo.invalid'])})
