import crypto from 'node:crypto'
import { Router } from 'express'
import { pool } from '../db.js'
import { auth } from '../middleware/auth.js'
import { requireProject,sendProjectError } from '../middleware/project.js'
import { createApprovalDecision } from '../marketing/approvals.js'
import { getArtifact,transitionArtifact } from '../marketing/artifacts.js'
const r=Router();r.use(auth)
const fail=(res,e)=>{if(!sendProjectError(res,e))res.status(e.code==='INVALID_TRANSITION'?409:400).json({error:e.message,code:e.code||'INVALID_REQUEST'})}
r.get('/:projectId',async(req,res)=>{try{await requireProject(req,req.params.projectId);const {rows}=await pool.query(`SELECT a.*,d.decision AS latest_decision,d.comment AS decision_comment,d.decided_at FROM marketing_artifacts a LEFT JOIN LATERAL (SELECT * FROM marketing_approval_decisions WHERE artifact_id=a.id AND artifact_version=a.artifact_version AND user_id=a.user_id AND project_id=a.project_id ORDER BY decided_at DESC LIMIT 1) d ON TRUE WHERE a.user_id=$1 AND a.project_id=$2 AND a.status IN ('draft','rejected') ORDER BY a.updated_at DESC`,[req.user.id,req.params.projectId]);res.json({pending:rows})}catch(e){fail(res,e)}})
r.post('/:projectId/decisions',async(req,res)=>{const client=await pool.connect();try{await requireProject(req,req.params.projectId,client);const ids=[...new Set(Array.isArray(req.body.artifactIds)?req.body.artifactIds:[req.body.artifactId])].filter(Boolean);if(!ids.length)throw new Error('artifactId or artifactIds is required');const groupId=ids.length>1?crypto.randomUUID():null;await client.query('BEGIN');const decisions=[];for(const id of ids){const artifact=await getArtifact({id,userId:req.user.id,projectId:req.params.projectId,db:client});if(!artifact)throw Object.assign(new Error('Artifact not found'),{code:'ARTIFACT_NOT_FOUND'});const decision=createApprovalDecision({userId:req.user.id,projectId:req.params.projectId,campaignId:artifact.campaignId,artifactId:id,artifactVersion:artifact.artifactVersion,decision:req.body.decision,comment:req.body.comment,groupId});const inserted=await client.query(`INSERT INTO marketing_approval_decisions (id,user_id,project_id,campaign_id,artifact_id,artifact_version,decision,comment,group_id,decided_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) ON CONFLICT (user_id,project_id,artifact_id,artifact_version,decision) DO UPDATE SET id=marketing_approval_decisions.id RETURNING *`,[decision.id,decision.userId,decision.projectId,decision.campaignId,decision.artifactId,decision.artifactVersion,decision.decision,decision.comment,decision.groupId,decision.decidedAt]);const target=decision.decision==='approved'?'approved':'rejected';if(artifact.status==='draft'||(artifact.status==='rejected'&&target==='approved'))await transitionArtifact({id,userId:req.user.id,projectId:req.params.projectId,to:target,db:client});decisions.push(inserted.rows[0])}await client.query('COMMIT');res.status(201).json({decisions,groupId})}catch(e){await client.query('ROLLBACK').catch(()=>{});fail(res,e)}finally{client.release()}})
export default r
