import { Router } from 'express'
import { pool } from '../db.js'
import { auth } from '../middleware/auth.js'
import { requireProject, sendProjectError } from '../middleware/project.js'
import { createCampaign, transitionCampaign } from '../marketing/campaignDomain.js'

const r = Router(); r.use(auth)
const fail = (res, error) => { if (!sendProjectError(res, error)) res.status(error.code === 'INVALID_TRANSITION' ? 409 : 400).json({ error: error.message, code: error.code || 'INVALID_REQUEST' }) }
const decode = row => row && ({ id:row.id,userId:row.user_id,projectId:row.project_id,schemaVersion:row.schema_version,name:row.name,objective:row.objective,status:row.status,context:row.context,createdAt:row.created_at,updatedAt:row.updated_at })

r.get('/:projectId', async (req,res) => { try { await requireProject(req,req.params.projectId); const {rows}=await pool.query('SELECT * FROM marketing_campaigns WHERE user_id=$1 AND project_id=$2 ORDER BY updated_at DESC',[req.user.id,req.params.projectId]); res.json({campaigns:rows.map(decode)}) } catch(e){fail(res,e)} })
r.post('/:projectId', async (req,res) => { try { await requireProject(req,req.params.projectId); const campaign=createCampaign({...req.body,userId:req.user.id,projectId:req.params.projectId}); const {rows}=await pool.query(`INSERT INTO marketing_campaigns (id,schema_version,user_id,project_id,name,objective,status,context) VALUES ($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *`,[campaign.id,campaign.schemaVersion,campaign.userId,campaign.projectId,campaign.name,campaign.objective,campaign.status,JSON.stringify(campaign.context)]); res.status(201).json(decode(rows[0])) } catch(e){fail(res,e)} })
r.get('/:projectId/:id', async (req,res) => { try { await requireProject(req,req.params.projectId); const scoped=[req.params.id,req.user.id,req.params.projectId]; const [campaign,artifacts,planner,queue,performance,approvals]=await Promise.all([pool.query('SELECT * FROM marketing_campaigns WHERE id=$1 AND user_id=$2 AND project_id=$3',scoped),pool.query('SELECT * FROM marketing_artifacts WHERE campaign_id=$1 AND user_id=$2 AND project_id=$3 ORDER BY updated_at DESC',scoped),pool.query("SELECT * FROM posts WHERE campaign_id=$1 AND user_id=$2 AND project_id=$3 AND status IN ('draft','scheduled') ORDER BY scheduled_at",scoped),pool.query("SELECT * FROM posts WHERE campaign_id=$1 AND user_id=$2 AND project_id=$3 AND status NOT IN ('draft','scheduled') ORDER BY updated_at DESC",scoped),pool.query('SELECT * FROM marketing_performance_events WHERE campaign_id=$1 AND user_id=$2 AND project_id=$3 ORDER BY occurred_at DESC',scoped),pool.query('SELECT * FROM marketing_approval_decisions WHERE campaign_id=$1 AND user_id=$2 AND project_id=$3 ORDER BY decided_at DESC',scoped)]); if(!campaign.rows[0]) return res.status(404).json({error:'Campaign not found'}); res.json({campaign:decode(campaign.rows[0]),artifacts:artifacts.rows,plannerEntries:planner.rows,queueEntries:queue.rows,performanceEvents:performance.rows,approvals:approvals.rows,launchPlan:artifacts.rows.find(a=>a.type==='launch')||null}) } catch(e){fail(res,e)} })
r.patch('/:projectId/:id/status', async(req,res)=>{try{await requireProject(req,req.params.projectId);const {rows}=await pool.query('SELECT * FROM marketing_campaigns WHERE id=$1 AND user_id=$2 AND project_id=$3',[req.params.id,req.user.id,req.params.projectId]);if(!rows[0])return res.status(404).json({error:'Campaign not found'});const next=transitionCampaign(decode(rows[0]),req.body.status);const updated=await pool.query('UPDATE marketing_campaigns SET status=$1,updated_at=$2 WHERE id=$3 AND user_id=$4 AND project_id=$5 RETURNING *',[next.status,next.updatedAt,req.params.id,req.user.id,req.params.projectId]);res.json(decode(updated.rows[0]))}catch(e){fail(res,e)}})
export default r
