import crypto from 'node:crypto'
import { Router } from 'express'
import { auth } from '../middleware/auth.js'
import { requireProject, sendProjectError } from '../middleware/project.js'
import { validateCrawlUrl } from '../services/safeCrawler.js'
import { createJob } from '../jobs/jobStore.js'
import { getMarketingProfile } from '../marketing/profileStore.js'
import { pool } from '../db.js'
const r = Router(); r.use(auth)
const decode = x => ({ id:x.id, projectId:x.project_id, name:x.name, websiteUrl:x.website_url, status:x.status, intelligence:x.intelligence, evidence:x.evidence, analyzedAt:x.analyzed_at, createdAt:x.created_at, updatedAt:x.updated_at })
const fail = (res,e) => { if (!sendProjectError(res,e)) res.status(e.status || 400).json({ error:e.code || e.status ? e.message : 'Request could not be completed', code:e.code || 'INVALID_REQUEST' }) }
r.get('/:projectId', async(req,res) => { try { await requireProject(req,req.params.projectId); const {rows}=await pool.query('SELECT * FROM competitors WHERE user_id=$1 AND project_id=$2 ORDER BY updated_at DESC',[req.user.id,req.params.projectId]); res.json({competitors:rows.map(decode)}) } catch(e){fail(res,e)} })
r.post('/:projectId', async(req,res) => { try { await requireProject(req,req.params.projectId); const url=await validateCrawlUrl(req.body.websiteUrl); const {rows}=await pool.query(`INSERT INTO competitors (id,user_id,project_id,name,website_url) VALUES ($1,$2,$3,$4,$5) ON CONFLICT(project_id,website_url) DO UPDATE SET name=EXCLUDED.name,updated_at=NOW() WHERE competitors.user_id=EXCLUDED.user_id RETURNING *`,[crypto.randomUUID(),req.user.id,req.params.projectId,String(req.body.name||url.hostname).trim(),url.href]); if(!rows[0]) return res.status(404).json({error:'Competitor not found'}); res.status(201).json(decode(rows[0])) } catch(e){fail(res,e)} })
r.post('/:projectId/:id/analyze', async(req,res) => { try { const projectId=req.params.projectId; await requireProject(req,projectId); const found=await pool.query('SELECT * FROM competitors WHERE id=$1 AND user_id=$2 AND project_id=$3',[req.params.id,req.user.id,projectId]); if(!found.rows[0])return res.status(404).json({error:'Competitor not found'}); const profile=await getMarketingProfile({userId:req.user.id,projectId}); const job=await createJob({userId:req.user.id,projectId,kind:'marketing.competitor-analysis',provider:'deterministic-local',model:'competitor-fixture-v1',idempotencyKey:req.get('Idempotency-Key')||`competitor:${req.params.id}`,input:{competitorId:req.params.id,websiteUrl:found.rows[0].website_url,profileVersion:profile.version}}); const intelligence={positioning:'Pending verified website evidence',valuePropositions:[],offers:[],messaging:[],contentThemes:[],channels:[],seoObservations:[],strengths:[],weaknesses:[],opportunities:['Collect verified website evidence'],differentiationOpportunities:['Compare evidence against the Marketing Profile'],comparison:{marketingProfileVersion:profile.version}}; const {rows}=await pool.query(`UPDATE competitors SET status='queued',intelligence=$1,evidence='[]'::jsonb,updated_at=NOW() WHERE id=$2 AND user_id=$3 AND project_id=$4 RETURNING *`,[JSON.stringify(intelligence),req.params.id,req.user.id,projectId]); res.status(202).json({competitor:decode(rows[0]),jobId:job.id,mock:true,note:'No website was contacted; durable job queued.'}) } catch(e){fail(res,e)} })
export default r
