import { Router } from 'express'
import { pool } from '../db.js'
import { auth } from '../middleware/auth.js'
import { requireProject, sendProjectError } from '../middleware/project.js'
import { SOSY_IDENTITY } from '../sosy/identity.js'
import { buildSosyDraft, createSosyDelegation, transitionSosyDelegation } from '../sosy/domain.js'
import { getSosyDelegation, listSosyDelegations, saveSosyDelegation, updateSosyDelegation } from '../sosy/store.js'
import { getArtifact, saveArtifact } from '../marketing/artifacts.js'
import { createJob, transitionJob } from '../jobs/jobStore.js'
import { recordProjectActivity } from '../lib/projectActivity.js'
const r=Router();r.use(auth)
const fail=(res,error)=>{if(sendProjectError(res,error))return;const status=['INVALID_TASK_TYPE','INVALID_OBJECTIVE','INVALID_CHANNELS','INVALID_LANGUAGES','SOURCE_ARTIFACT_REQUIRED','INVALID_STATUS_TRANSITION'].includes(error?.code)?400:500;if(status===500)console.error('Sosy operation failed',{code:error?.code||'UNKNOWN'});res.status(status).json({error:status===500?'Sosy operation failed':error.message,code:error?.code||'SOSY_OPERATION_FAILED'})}
r.get('/identity',(_req,res)=>res.json({identity:SOSY_IDENTITY}))
r.get('/:projectId/delegations',async(req,res)=>{try{await requireProject(req,req.params.projectId);res.json({delegations:await listSosyDelegations({userId:req.user.id,projectId:req.params.projectId,tonyPlanId:req.query.tonyPlanId,limit:req.query.limit})})}catch(error){fail(res,error)}})
r.post('/:projectId/delegations',async(req,res)=>{try{const projectId=req.params.projectId;await requireProject(req,projectId);const input=req.body||{};if(input.tonyPlanId){const owned=await pool.query('SELECT id FROM tony_execution_plans WHERE id=$1 AND user_id=$2 AND project_id=$3',[input.tonyPlanId,req.user.id,projectId]);if(!owned.rows[0])return res.status(404).json({error:'Tony plan not found',code:'TONY_PLAN_NOT_FOUND'})}if(input.campaignId){const owned=await pool.query('SELECT id FROM marketing_campaigns WHERE id=$1 AND user_id=$2 AND project_id=$3',[input.campaignId,req.user.id,projectId]);if(!owned.rows[0])return res.status(404).json({error:'Campaign not found',code:'CAMPAIGN_NOT_FOUND'})}if(input.sourceArtifactId&&!await getArtifact({id:input.sourceArtifactId,userId:req.user.id,projectId}))return res.status(404).json({error:'Source artifact not found',code:'SOURCE_ARTIFACT_NOT_FOUND'});const delegation=await saveSosyDelegation(createSosyDelegation({...input,userId:req.user.id,projectId}));await recordProjectActivity({userId:req.user.id,projectId,eventType:'sosy_delegation_created',subjectType:'sosy_delegation',subjectId:delegation.id,summary:'Sosy received a draft social task',metadata:{taskType:delegation.taskType,channels:delegation.channels,languages:delegation.languages},dedupeKey:`sosy:created:${delegation.id}`});res.status(201).json({delegation})}catch(error){fail(res,error)}})
r.post('/:projectId/delegations/:id/run',async(req,res)=>{const{projectId,id}=req.params;let working=null;try{await requireProject(req,projectId);const current=await getSosyDelegation({id,userId:req.user.id,projectId});if(!current)return res.status(404).json({error:'Sosy delegation not found',code:'SOSY_DELEGATION_NOT_FOUND'});if(!['assigned','planned','queued'].includes(current.status))return res.status(409).json({error:'Sosy delegation is not runnable',code:'INVALID_STATUS_TRANSITION'});working=transitionSosyDelegation(current,'working');if(!await updateSosyDelegation({delegation:working,from:current.status}))return res.status(409).json({error:'Sosy delegation state changed',code:'DELEGATION_CONFLICT'});const job=await createJob({userId:req.user.id,projectId,kind:'marketing.social',provider:'deterministic-local',model:'sosy-draft-v1',idempotencyKey:req.get('Idempotency-Key')||`sosy:${id}`,input:{delegationId:id,taskType:current.taskType}});const activeJob=job.status==='queued'?await transitionJob({id:job.id,userId:req.user.id,projectId,from:'queued',to:'running'}):job;const sourceArtifact=current.sourceArtifactId?await getArtifact({id:current.sourceArtifactId,userId:req.user.id,projectId}):null;const draft=buildSosyDraft(current,{sourceArtifact});const artifact=await saveArtifact({userId:req.user.id,projectId,campaignId:current.campaignId,type:draft.artifactType,purpose:draft.purpose,channel:draft.channel,content:draft.content,provenance:{jobId:job.id},provider:'deterministic-local',model:'sosy-draft-v1'});await transitionJob({id:job.id,userId:req.user.id,projectId,from:activeJob.status,to:'succeeded',artifacts:[{id:artifact.id,type:artifact.type}]});const waiting=transitionSosyDelegation(working,'waiting_approval',{resultArtifactId:artifact.id});const delegation=await updateSosyDelegation({delegation:waiting,from:'working'});await recordProjectActivity({userId:req.user.id,projectId,eventType:'sosy_draft_completed',subjectType:'marketing_artifact',subjectId:artifact.id,summary:'Sosy created a draft awaiting approval',metadata:{delegationId:id,taskType:current.taskType},dedupeKey:`sosy:completed:${id}`});res.json({delegation,artifact,job:{...job,status:'succeeded'},mock:true,requiresApproval:true})}catch(error){if(working){try{await updateSosyDelegation({delegation:transitionSosyDelegation(working,'failed',{error}),from:'working'})}catch{}}fail(res,error)}})
export default r
