ALTER TABLE ai_jobs
  ADD COLUMN IF NOT EXISTS max_retries INTEGER NOT NULL DEFAULT 2 CHECK (max_retries >= 0);
ALTER TABLE ai_jobs
  ADD COLUMN IF NOT EXISTS timeout_ms INTEGER NOT NULL DEFAULT 60000 CHECK (timeout_ms > 0);
