import crypto from 'node:crypto'
export const JOB_STATUSES = Object.freeze(['queued', 'running', 'succeeded', 'failed', 'cancelled'])
const TRANSITIONS = Object.freeze({ queued: ['running', 'cancelled'], running: ['succeeded', 'failed', 'cancelled'], succeeded: [], failed: ['queued'], cancelled: [] })
export class JobError extends Error { constructor(code, message, { retryable = false, details } = {}) { super(message); this.name = 'JobError'; this.code = code; this.retryable = retryable; this.details = details } }
export function normalizeJobError(error) { if (error instanceof JobError) return { code: error.code, message: error.message, retryable: error.retryable, ...(error.details ? { details: error.details } : {}) }; const timeout = error?.name === 'AbortError' || error?.name === 'TimeoutError'; return { code: timeout ? 'PROVIDER_TIMEOUT' : 'PROVIDER_ERROR', message: timeout ? 'Provider timed out' : 'Provider failed', retryable: true } }
export function assertTransition(from, to) { if (!JOB_STATUSES.includes(from) || !JOB_STATUSES.includes(to) || !TRANSITIONS[from].includes(to)) throw new JobError('INVALID_JOB_TRANSITION', `Cannot transition job from ${from} to ${to}`) }
export function createJobRecord({ userId, projectId, kind, provider, model = null, input = {}, idempotencyKey, timeoutMs = 60_000, maxRetries = 2, now = new Date().toISOString(), id = crypto.randomUUID() }) { if (!userId || !projectId || !kind || !provider || !idempotencyKey) throw new TypeError('userId, projectId, kind, provider and idempotencyKey are required'); if (!Number.isInteger(timeoutMs) || timeoutMs < 1 || !Number.isInteger(maxRetries) || maxRetries < 0) throw new TypeError('timeoutMs and maxRetries must be positive integers'); return { id, userId, projectId, kind, provider, model, input, status: 'queued', idempotencyKey, timeoutMs, maxRetries, retryCount: 0, artifacts: [], usage: {}, error: null, createdAt: now, startedAt: null, finishedAt: null } }
// Offline provider used only by tests/development. Live providers implement the same boundary.
export function createMockJobProvider({ result = { artifacts: [] }, fail = null } = {}) { return { name: 'mock', async submit(job) { if (fail) throw fail; return { providerJobId: `mock:${job.id}`, state: 'succeeded', result } }, async poll() { return { state: 'succeeded', result } }, async cancel() { return { state: 'cancelled' } } } }
