import crypto from 'node:crypto'
import { SOSY_IDENTITY } from './identity.js'
export const SOSY_DELEGATION_SCHEMA_VERSION = 1
export const SOSY_TASK_TYPES = Object.freeze(['content.create', 'content.adapt', 'calendar.propose'])
export const SOSY_CHANNELS = Object.freeze(['facebook','instagram','linkedin','tiktok','x','threads','pinterest','youtube'])
export const SOSY_STATUSES = Object.freeze(['assigned','working','waiting_approval','planned','queued','completed','failed'])
const channelSet = new Set(SOSY_CHANNELS)
const languagePattern = /^[a-z]{2,3}(?:-[A-Z]{2})?$/
function domainError(code,message){const error=new TypeError(message);error.code=code;return error}
const normalizeLanguage=value=>{const[language,region]=String(value||'').trim().replace('_','-').split('-');const normalized=region?`${language.toLowerCase()}-${region.toUpperCase()}`:language.toLowerCase();if(!languagePattern.test(normalized))throw domainError('INVALID_LANGUAGES','languages must contain valid language tags');return normalized}
export function normalizeLanguages(input){if(!input||typeof input!=='object'||Array.isArray(input))throw domainError('INVALID_LANGUAGES','languages must define conversationLanguage and outputLanguage');return{conversationLanguage:normalizeLanguage(input.conversationLanguage),outputLanguage:normalizeLanguage(input.outputLanguage)}}
export function normalizeChannels(input){const values=Array.isArray(input)&&input.length?input:['instagram'];const normalized=[...new Set(values.map(value=>String(value||'').trim().toLowerCase()))];if(!normalized.length||normalized.length>SOSY_CHANNELS.length||normalized.some(value=>!channelSet.has(value)))throw domainError('INVALID_CHANNELS','channels contain an unsupported social channel');return normalized}
export function createSosyDelegation(input,{id=crypto.randomUUID(),now=new Date().toISOString()}={}){if(!input?.userId||!input?.projectId)throw domainError('PROJECT_CONTEXT_REQUIRED','Sosy requires an owned project context');if(!SOSY_TASK_TYPES.includes(input.taskType))throw domainError('INVALID_TASK_TYPE','Unsupported Sosy task type');const objective=String(input.objective||'').trim();if(!objective||objective.length>2000)throw domainError('INVALID_OBJECTIVE','objective is required and must be at most 2000 characters');const channels=normalizeChannels(input.channels),languages=normalizeLanguages(input.languages);if(input.taskType==='content.adapt'&&!input.sourceArtifactId)throw domainError('SOURCE_ARTIFACT_REQUIRED','content adaptation requires a source artifact');return{id,schemaVersion:SOSY_DELEGATION_SCHEMA_VERSION,specialist:SOSY_IDENTITY.id,userId:input.userId,projectId:input.projectId,campaignId:input.campaignId||null,tonyPlanId:input.tonyPlanId||null,sourceArtifactId:input.sourceArtifactId||null,taskType:input.taskType,objective,channels,languages,schedule:input.schedule&&typeof input.schedule==='object'?input.schedule:null,status:'assigned',resultArtifactId:null,error:null,createdAt:now,updatedAt:now}}
export function transitionSosyDelegation(delegation,to,{error=null,resultArtifactId=null,now=new Date().toISOString()}={}){const allowed={assigned:['planned','queued','working','failed'],planned:['queued','working','failed'],queued:['working','failed'],working:['waiting_approval','completed','failed'],waiting_approval:['completed','failed'],completed:[],failed:[]};if(!delegation||!SOSY_STATUSES.includes(to)||!allowed[delegation.status]?.includes(to))throw domainError('INVALID_STATUS_TRANSITION','Invalid Sosy delegation status transition');if(['waiting_approval','completed'].includes(to)&&!resultArtifactId)throw domainError('RESULT_REQUIRED','Sosy approval state requires a draft artifact result');return{...delegation,status:to,resultArtifactId:resultArtifactId||delegation.resultArtifactId,error:to==='failed'?String(error||'Sosy task failed').slice(0,500):null,updatedAt:now}}
const label=channel=>({instagram:'Instagram',facebook:'Facebook',linkedin:'LinkedIn',tiktok:'TikTok',x:'X',threads:'Threads',pinterest:'Pinterest',youtube:'YouTube'}[channel])
export function buildSosyDraft(delegation,{sourceArtifact=null}={}){if(!delegation||delegation.specialist!==SOSY_IDENTITY.id)throw domainError('INVALID_DELEGATION','Valid Sosy delegation is required');if(delegation.taskType==='content.adapt'&&!sourceArtifact)throw domainError('SOURCE_ARTIFACT_REQUIRED','Source artifact was not found');const sourceText=sourceArtifact?.content?.socialCopy||sourceArtifact?.content?.caption||sourceArtifact?.content?.body||delegation.objective,language=delegation.languages.outputLanguage;const variants=delegation.channels.map(channel=>({channel,language,text:`[${label(channel)} · ${language}] ${String(sourceText).trim()}`,status:'draft'}));if(delegation.taskType==='calendar.propose')return{artifactType:'social',purpose:delegation.objective,channel:null,content:{schemaVersion:1,kind:'social-calendar-proposal',languages:delegation.languages,channels:delegation.channels,schedule:delegation.schedule,entries:variants.map((variant,index)=>({...variant,slot:index+1}))}};return{artifactType:'social',purpose:delegation.objective,channel:delegation.channels.length===1?delegation.channels[0]:null,content:{schemaVersion:1,kind:delegation.taskType==='content.adapt'?'multi-channel-adaptation':'social-content-draft',sourceArtifactId:delegation.sourceArtifactId,languages:delegation.languages,channels:delegation.channels,variants}}}
